name: Maven Build and Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: paulhatch/semantic-version@v5.1.0
      id: generate-version
      with:
        tag_prefix: "v"
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'
    - name: Deploy to Github Package Registry
      run: mvn -V -B -X clean deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEM_VERSION: ${{ steps.generate-version.outputs.version }}
    - name: Create tag and push
      run: git tag v${{ steps.generate-version.outputs.version }} && git push --tags || echo "tag already exist"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
